#!/bin/bash

SCRIPTNAME=`basename $0`
usage="$SCRIPTNAME -precheck | -exec | -postcheck 
  
   -precheck   :check if dataguard configuration is ready for switchover
   -exec       :execute switchover
   -postcheck  :check if dataguard configuration is ready after switchover

"

####################################################################
## Verify the input parameters
####################################################################
if [ $# -eq 1 ]
then
  PARAM=$1
else
  echo "Usage: $usage"
  exit 1
fi

if [[ $PARAM == "-precheck" ]] || [[ $PARAM == "-exec" ]] || [[ $PARAM == "-postcheck" ]]
then 
  echo ""
else 
  echo "Usage: $usage"
  exit 1
fi


####################################################################
## call senv env.
####################################################################
. /DBA/nest/senv/senv_profile && . $SENV_HOME/senv.sh QUIET o $SRV_SID

if [ $? -ne 0 ]
then
  echo "Unknown Senv-Environment: $SRV_SID. Exiting"
  exit 1
fi


####################################################################
## parameters
####################################################################
LOW_SID=`echo $SRV_SID|tr [:upper:] [:lower:]`
ORAPWD=`nestpwd --get sys --batch`
role="PHYSICAL STANDBY"
tempfile="/WORK/TMP/$SCRIPTNAME.tmp"

####################################################################
## basic check if database is running
####################################################################
ps -ae -o args | grep -w ora_pmon_$ORACLE_SID | grep -v grep >/dev/null
if [ $? -ne 0 ]
then
  echo "Database pmon not running $ORACLE_SID, Exit 1" 
  exit 1;
fi

if [[ $PARAM == "-precheck" ]] || [[ $PARAM == "-exec" ]]
then

####################################################################
## check if this is a dataguard configuration
####################################################################
s+ -a<<EOI>$tempfile
select 'DGCONF:'||DATAGUARD_BROKER from v\$database;
EOI
cat $tempfile |egrep "^DGCONF:ENABLED" 2>&1 > /dev/null


if [ $? -ne 0 ]
then
  echo "database $SRV_SID is not a dataguard, exit 0 "
  exit 0;
else
  echo "database $SRV_SID is a dataguard configuration, continue with checks... "
fi




####################################################################
## check database role
####################################################################
s+ -a<<EOI>$tempfile
select 'ROLE:'||database_role from v\$database;
EOI
cat $tempfile |egrep "^ROLE:$role" 2>&1 > /dev/null

if [ $? -ne 0 ]
then
  echo "database role for $SRV_SID is not \"$role\", exit 99"
  ## Exit 99 for streamworks control
  exit 99;
else
  echo "database role for $SRV_SID is \"$role\", continue with checks..."
fi


####################################################################
## Check dataguard status
####################################################################
echo "check dataguard status..."
(
echo "dgmgrl<<EOI"
echo "connect sys/$ORAPWD@${SRV_SID}_DG"
echo "show configuration"
echo "EOI"
) > $tempfile

. $tempfile|egrep ^SUCCESS 2>&1 > /dev/null
if [ $? -ne 0 ]
then
  echo "dataguard status not ok , exit 	1"
  exit 1;
else
  echo "dataguard status ok, continue with checks..."
fi


####################################################################
## Check database status
####################################################################
echo "check database status..."
(
echo "dgmgrl<<EOI"
echo "connect sys/$ORAPWD@${SRV_SID}_DG"
echo "show database $LOW_SID"
echo "EOI"
) > $tempfile

. $tempfile|egrep ^SUCCESS 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  echo "database status not ok , exit 1"
  exit 1;
else
  echo "database status  ok, continue with checks..."
fi

####################################################################
## validate command
####################################################################
echo "execute validate database ..."
(
echo "dgmgrl<<EOI"
echo "connect sys/$ORAPWD@${SRV_SID}_DG"
echo "validate database $LOW_SID"
echo "EOI"
) > $tempfile
# . $tempfile|egrep "Ready for Switchover:"2>&1 > /dev/null
. $tempfile|egrep "^[[:space:]]+Ready for Switchover:[[:space:]]+Yes"
if [ $? -ne 0 ]; then
  echo "Switchover status not ok , exit 1"
  exit 1;
else
  echo "Switchover status ok, ready for switchover"
fi

fi



if [[ $PARAM == "-exec" ]]
then 
echo "switchover to $LOW_SID"
(
echo "dgmgrl<<EOI"
echo "connect sys/$ORAPWD@${SRV_SID}_DG"
echo "switchover to $LOW_SID"
echo "EOI"
) > $tempfile

. $tempfile
fi


if [[ $PARAM == "-postcheck" ]]
then
echo "sleeping 10sec"
sleep 10
echo "execute validate database ..."
(
echo "dgmgrl<<EOI"
echo "connect sys/$ORAPWD@${SRV_SID}_DG"
echo "validate database $LOW_SID"
echo "EOI"
) > $tempfile
# . $tempfile|egrep "Ready for Switchover:"2>&1 > /dev/null
. $tempfile|egrep "^[[:space:]]+Ready for Switchover:[[:space:]]+Yes"
if [ $? -ne 0 ]; then
  echo "Switchover status not ok , exit 1"
  exit 1;
else
  echo "Switchover status ok, ready for switchover"
fi

fi

rm -f $tempfile
